# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('due_date', models.DateTimeField(verbose_name='Fecha Limite')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_create_user', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasValidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_create_user', to=settings.AUTH_USER_MODEL)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.Pregunta')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuesta_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='respuestasvalidas',
            unique_together=set([('pregunta', 'text')]),
        ),
    ]
